version: 0.2

env:
  variables:
    NODE_ENV: production

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm ci
  pre_build:
    commands:
      - echo Running lint checks...
      - npm run lint
  build:
    commands:
      - echo Building Next.js application...
      - npm run build
  post_build:
    commands:
      - echo Build completed at `date`

artifacts:
  files:
    - '**/*'
  base-directory: '.next'
  discard-paths: no

